evict ingress-nginx-controller from kube-downscaler scope
giantswarm/kyverno-policies-connectivity pull request #162
Opened 2024-12-26 11:12 UTC by QuantumEnigmaa

### Checklist

- [x] Update changelog in CHANGELOG.md.

2024-12-26 12:41 UTC, mcharriere requested changes
any reason for not setting this into the config repo?

I think that's a better suited place for this kind of settings.

2024-12-26 13:15 UTC, QuantumEnigmaa commented
> setting this into the config repo

Do you mean as an extraObject in the `kyverno-policies-connectivity` ?

2024-12-26 19:46 UTC, mcharriere commented
No, sorry. I meant either:

- [in the shared-config repo](https://github.com/giantswarm/shared-configs/blob/main/default/apps/ingress-nginx/configmap-values.yaml.template) for gobal config (affecting all MCs)
- or in the customer specific config repos to target specific MCs

There you should be able to use the values `controller.annotations` and `controller.autoscaling.annotations` to set the respective labels.

2025-01-02 14:59 UTC, QuantumEnigmaa commented
Ok I'll do that then :)

2025-01-02 15:04 UTC, closed without merging